### ISSUE TITLE
flat-map npm bundle?

### ISSUE THREAD

**Issue by dts** [FallingSnow/CPSC474_Project_2#1]
(Sorry to contact you in such a bizarre way - I couldn't find an email and your twitter handle looks abandoned.)  I am doing some research in static analysis and npm packages.  Any chance you still have a copy of the malicious code as-uploaded-to-npm?  Drop me a line at dan@brd.com, @dandisagrees or here.

**Comment by FallingSnow** [comment]
I tired to email you the source but it got blocked twice by antivirus.

This is the only copy of the original source code I could find in my files. Seems to be unmodified other than the unminified source in index.min.js.

[flatmap-stream@0.1.1.zip](https://github.com/FallingSnow/CPSC474_Project_2/files/2642544/flatmap-stream.0.1.1.zip)

**Comment by dts** [comment]
Thank you so much!
